# Generated by Django 5.2.7 on 2025-12-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_price_date_checked_price_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store'),
        ),
        migrations.AlterField(
            model_name='price',
            name='url_on_store',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
