# Generated by Django 5.2.7 on 2025-12-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_price_store_alter_price_url_on_store'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
