# Generated by Django 5.2.7 on 2025-12-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_price_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
