# Generated by Django 5.2.7 on 2025-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_checked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
