# Generated by Django 5.2.7 on 2025-12-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alert_alert_activation_alert_last_checked_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_activation',
            new_name='price_alert',
        ),
    ]
