# Generated by Django 6.0.1 on 2026-01-30 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_alert_id_alter_category_id_alter_price_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='last_checked_price',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='price_alert',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_triggered',
            field=models.BooleanField(default=False, verbose_name='Tetiklendi mi?'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
